import './global.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { NavBar } from './components/NavBar/NavBar';

export const metadata = {
  title: 'Welcome to kwporównywarka',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
